server:
  port: 8080
spring:
  application:
    #name the project
    name: takie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/takeout?characterEncoding=utf8
      username: root
      password: cj

mybatis-plus:
  configuration:
    #turn the "_" in database's table name and field name into camel name
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
takie:
  path: D:\ToCs\projects\takeout\uploadFolder\